let mockData = [
    { id: 31, itemName: "GE Signa Architect 3.0T MRI Scanner", sku: "EQP-2941", category: "Equipment", department: "Radiology", supplier: "GE Healthcare", stockQuantity: 1, unit: "Unit", expiryDate: "N/A", form: "Unit", maxCapacity: 1, reorderPoint: 0, storageLocation: { warehouse: "Main Wing", aisle: "Imaging Suite A", rack: "Room 102", shelf: "", zone: "" }, handlingRequirements: ["High Value", "Specialized Cooling"], vendorId: "V-9912", leadTime: "90 Days", unitPrice: 1500000.00, manufacturer: "GE Healthcare", description: "High-end 3.0 Tesla magnetic resonance imaging system. Used for advanced neuro, MSK, and body imaging. Requires specialized cooling infrastructure.", serialNumber: "SN-MAG-30T-2021-8842", assetTag: "AST-RD-004", departmentAssignment: "Radiology", location: "Main Wing, Imaging Suite A (Room 102)", maintenanceSchedule: "Bi-Annual", lastServiced: "2023-08-15", warrantyExpiration: "2028-12-31", status: "Operational", image: "/placeholder-mri.png" },
    { id: 1, itemName: "Amoxicillin 500mg", sku: "MED-AMX-001", category: "Medicine", department: "Pharmacy", supplier: "PharmaCorp Inc.", stockQuantity: 1250, unit: "Boxes", expiryDate: "2025-10-15", form: "Capsule", maxCapacity: 2000, reorderPoint: 400, storageLocation: { warehouse: "Main Dispensary", aisle: "1", rack: "A", shelf: "02", zone: "B" }, handlingRequirements: ["Below 25°C", "Dry Place"], vendorId: "V-1023", leadTime: "2-4 Days", unitPrice: 3.20 },
    { id: 2, itemName: "Surgical Masks (N95)", sku: "SUP-MSK-N95", category: "Medical Supplies", department: "Central Supply", supplier: "MedEquip Global", stockQuantity: 45, unit: "Cartons", expiryDate: "N/A", form: "Box", maxCapacity: 500, reorderPoint: 100, storageLocation: { warehouse: "Supply Room", aisle: "2", rack: "C", shelf: "01", zone: "A" }, handlingRequirements: ["Dry Place"], vendorId: "V-2211", leadTime: "5-7 Days", unitPrice: 15.00 },
    { id: 3, itemName: "Digital Thermometers", sku: "EQP-THM-04", category: "Equipment", department: "Pediatrics", supplier: "MedEquip Global", stockQuantity: 210, unit: "Units", expiryDate: "N/A", form: "Unit", maxCapacity: 300, reorderPoint: 50, storageLocation: { warehouse: "Equipment Storage", aisle: "1", rack: "D", shelf: "05", zone: "C" }, handlingRequirements: ["Fragile"], vendorId: "V-2211", leadTime: "7-10 Days", unitPrice: 25.50 },
    { id: 4, itemName: "Ibuprofen 200mg", sku: "MED-IBU-200", category: "Medicine", department: "Pharmacy", supplier: "PharmaCorp Inc.", stockQuantity: 0, unit: "Boxes", expiryDate: "2024-12-01", form: "Tablet", maxCapacity: 1500, reorderPoint: 300, storageLocation: { warehouse: "Main Dispensary", aisle: "3", rack: "B", shelf: "02", zone: "A" }, handlingRequirements: ["Below 25°C"], vendorId: "V-1023", leadTime: "2-4 Days", unitPrice: 2.10 },
    { id: 5, itemName: "Sterile Syringes 5ml", sku: "SUP-SYR-005", category: "Medical Supplies", department: "ICU", supplier: "BioLab Solutions", stockQuantity: 5000, unit: "Packs", expiryDate: "2027-05-20", form: "Pack", maxCapacity: 10000, reorderPoint: 2000, storageLocation: { warehouse: "Supply Room", aisle: "4", rack: "A", shelf: "01", zone: "B" }, handlingRequirements: ["Sterile"], vendorId: "V-3044", leadTime: "3-5 Days", unitPrice: 8.75 },
    { id: 6, itemName: "Wheelchairs", sku: "EQP-WHL-01", category: "Equipment", department: "Emergency", supplier: "MobilityPlus", stockQuantity: 15, unit: "Units", expiryDate: "N/A", form: "Unit", maxCapacity: 50, reorderPoint: 10, storageLocation: { warehouse: "Equipment Storage", aisle: "5", rack: "A", shelf: "Floor", zone: "D" }, handlingRequirements: [], vendorId: "V-4055", leadTime: "14-21 Days", unitPrice: 250.00 },
    { id: 7, itemName: "Blood Collection Tubes", sku: "LAB-TUB-01", category: "Lab Supplies", department: "Laboratory", supplier: "BioLab Solutions", stockQuantity: 3200, unit: "Packs", expiryDate: "2026-03-10", form: "Pack", maxCapacity: 5000, reorderPoint: 1000, storageLocation: { warehouse: "Lab Storage", aisle: "1", rack: "B", shelf: "03", zone: "A" }, handlingRequirements: ["Below 25°C", "Fragile"], vendorId: "V-3044", leadTime: "3-5 Days", unitPrice: 12.00 },
    { id: 8, itemName: "Paracetamol 500mg", sku: "P-500-TAB", category: "Medicine", department: "Pharmacy", supplier: "MedPlus Ltd.", stockQuantity: 1250, unit: "Box (50s)", expiryDate: "2026-08-12", form: "Tablet", maxCapacity: 3000, reorderPoint: 500, storageLocation: { warehouse: "Main Dispensary", aisle: "3", rack: "B", shelf: "04", zone: "A" }, handlingRequirements: ["Below 25°C", "Dry Place"], vendorId: "V-8842", leadTime: "3-5 Days", unitPrice: 4.50 },
    { id: 9, itemName: "Latex Examination Gloves", sku: "SUP-GLV-01", category: "Medical Supplies", department: "Central Supply", supplier: "MedEquip Global", stockQuantity: 80, unit: "Cartons", expiryDate: "2028-01-01", form: "Carton", maxCapacity: 200, reorderPoint: 50, storageLocation: { warehouse: "Supply Room", aisle: "2", rack: "A", shelf: "02", zone: "C" }, handlingRequirements: ["Dry Place"], vendorId: "V-2211", leadTime: "5-7 Days", unitPrice: 45.00 },
    { id: 10, itemName: "ECG Machines", sku: "EQP-ECG-02", category: "Equipment", department: "Cardiology", supplier: "HeartTech", stockQuantity: 4, unit: "Units", expiryDate: "N/A", form: "Unit", maxCapacity: 10, reorderPoint: 2, storageLocation: { warehouse: "Equipment Storage", aisle: "2", rack: "B", shelf: "01", zone: "D" }, handlingRequirements: ["Fragile", "High Value"], vendorId: "V-5099", leadTime: "30 Days", unitPrice: 1200.00 },
    { id: 11, itemName: "Rapid COVID-19 Test Kits", sku: "LAB-COV-19", category: "Lab Supplies", department: "Laboratory", supplier: "BioLab Solutions", stockQuantity: 50, unit: "Kits", expiryDate: "2024-11-30", form: "Kit", maxCapacity: 500, reorderPoint: 100, storageLocation: { warehouse: "Lab Storage", aisle: "2", rack: "A", shelf: "01", zone: "B" }, handlingRequirements: ["Refrigerated"], vendorId: "V-3044", leadTime: "2-4 Days", unitPrice: 18.50 },
    { id: 12, itemName: "Insulin Syringes", sku: "SUP-INS-01", category: "Medical Supplies", department: "Pharmacy", supplier: "CarePlus Supplies", stockQuantity: 1500, unit: "Packs", expiryDate: "2026-12-01", form: "Pack", maxCapacity: 3000, reorderPoint: 500, storageLocation: { warehouse: "Main Dispensary", aisle: "4", rack: "C", shelf: "02", zone: "A" }, handlingRequirements: ["Sterile"], vendorId: "V-6011", leadTime: "3-5 Days", unitPrice: 9.20 },
    { id: 13, itemName: "Defibrillators", sku: "EQP-DEF-01", category: "Equipment", department: "Emergency", supplier: "LifeSaver Inc.", stockQuantity: 8, unit: "Units", expiryDate: "N/A", form: "Unit", maxCapacity: 15, reorderPoint: 3, storageLocation: { warehouse: "Equipment Storage", aisle: "3", rack: "A", shelf: "01", zone: "D" }, handlingRequirements: ["Fragile", "High Value"], vendorId: "V-7022", leadTime: "14-21 Days", unitPrice: 850.00 },
    { id: 14, itemName: "Azithromycin 250mg", sku: "MED-AZI-250", category: "Medicine", department: "Pharmacy", supplier: "PharmaCorp Inc.", stockQuantity: 600, unit: "Boxes", expiryDate: "2025-04-20", form: "Tablet", maxCapacity: 1500, reorderPoint: 300, storageLocation: { warehouse: "Main Dispensary", aisle: "3", rack: "A", shelf: "03", zone: "B" }, handlingRequirements: ["Below 25°C"], vendorId: "V-1023", leadTime: "2-4 Days", unitPrice: 5.40 },
    { id: 15, itemName: "Microscope Slides", sku: "LAB-SLD-01", category: "Lab Supplies", department: "Laboratory", supplier: "OpticLab", stockQuantity: 10000, unit: "Boxes", expiryDate: "N/A", form: "Box", maxCapacity: 20000, reorderPoint: 5000, storageLocation: { warehouse: "Lab Storage", aisle: "1", rack: "C", shelf: "04", zone: "A" }, handlingRequirements: ["Fragile"], vendorId: "V-8033", leadTime: "5-7 Days", unitPrice: 8.00 },
    { id: 16, itemName: "Hospital Beds", sku: "EQP-BED-05", category: "Equipment", department: "Inpatient", supplier: "MedComfort", stockQuantity: 45, unit: "Units", expiryDate: "N/A", form: "Unit", maxCapacity: 60, reorderPoint: 10, storageLocation: { warehouse: "Equipment Storage", aisle: "6", rack: "A", shelf: "Floor", zone: "D" }, handlingRequirements: [], vendorId: "V-9044", leadTime: "30-45 Days", unitPrice: 800.00 },
    { id: 17, itemName: "Gauze Pads", sku: "SUP-GZP-01", category: "Medical Supplies", department: "Central Supply", supplier: "CarePlus Supplies", stockQuantity: 200, unit: "Packs", expiryDate: "2029-05-15", form: "Pack", maxCapacity: 1000, reorderPoint: 200, storageLocation: { warehouse: "Supply Room", aisle: "3", rack: "B", shelf: "02", zone: "C" }, handlingRequirements: ["Sterile", "Dry Place"], vendorId: "V-6011", leadTime: "3-5 Days", unitPrice: 4.50 },
    { id: 18, itemName: "Ceftriaxone 1g Injection", sku: "MED-CEF-01", category: "Medicine", department: "Pharmacy", supplier: "GlobalPharma", stockQuantity: 150, unit: "Vials", expiryDate: "2025-02-28", form: "Vial", maxCapacity: 500, reorderPoint: 100, storageLocation: { warehouse: "Main Dispensary", aisle: "2", rack: "A", shelf: "01", zone: "B" }, handlingRequirements: ["Refrigerated"], vendorId: "V-1155", leadTime: "2-4 Days", unitPrice: 12.00 },
    { id: 19, itemName: "Urine Specimen Containers", sku: "LAB-URC-01", category: "Lab Supplies", department: "Laboratory", supplier: "BioLab Solutions", stockQuantity: 800, unit: "Boxes", expiryDate: "N/A", form: "Box", maxCapacity: 2000, reorderPoint: 400, storageLocation: { warehouse: "Lab Storage", aisle: "3", rack: "B", shelf: "02", zone: "A" }, handlingRequirements: ["Dry Place"], vendorId: "V-3044", leadTime: "3-5 Days", unitPrice: 15.00 },
    { id: 20, itemName: "Oxygen Cylinders", sku: "EQP-OXY-01", category: "Equipment", department: "Central Supply", supplier: "AirCare", stockQuantity: 0, unit: "Cylinders", expiryDate: "N/A", form: "Cylinder", maxCapacity: 100, reorderPoint: 20, storageLocation: { warehouse: "Equipment Storage", aisle: "4", rack: "A", shelf: "Floor", zone: "E" }, handlingRequirements: ["Hazardous Storage"], vendorId: "V-2266", leadTime: "1-2 Days", unitPrice: 150.00 },
    { id: 21, itemName: "IV Fluids (Normal Saline)", sku: "MED-IVF-01", category: "Medicine", department: "Emergency", supplier: "PharmaCorp Inc.", stockQuantity: 1200, unit: "Bags", expiryDate: "2025-11-10", form: "Bag", maxCapacity: 3000, reorderPoint: 500, storageLocation: { warehouse: "Supply Room", aisle: "1", rack: "D", shelf: "01", zone: "B" }, handlingRequirements: ["Below 25°C"], vendorId: "V-1023", leadTime: "2-4 Days", unitPrice: 2.50 },
    { id: 22, itemName: "Surgical Sutures", sku: "SUP-SUT-02", category: "Medical Supplies", department: "Surgery", supplier: "SurgiTech", stockQuantity: 60, unit: "Boxes", expiryDate: "2026-06-30", form: "Box", maxCapacity: 200, reorderPoint: 50, storageLocation: { warehouse: "Supply Room", aisle: "5", rack: "B", shelf: "03", zone: "A" }, handlingRequirements: ["Sterile"], vendorId: "V-3377", leadTime: "5-7 Days", unitPrice: 35.00 },
    { id: 23, itemName: "Ultrasound Gel", sku: "SUP-USG-01", category: "Medical Supplies", department: "Radiology", supplier: "MedEquip Global", stockQuantity: 300, unit: "Bottles", expiryDate: "2026-09-15", form: "Bottle", maxCapacity: 1000, reorderPoint: 200, storageLocation: { warehouse: "Supply Room", aisle: "2", rack: "C", shelf: "02", zone: "C" }, handlingRequirements: ["Below 25°C"], vendorId: "V-2211", leadTime: "5-7 Days", unitPrice: 6.50 },
    { id: 24, itemName: "Hemoglobin Test Strips", sku: "LAB-HGB-01", category: "Lab Supplies", department: "Laboratory", supplier: "BioLab Solutions", stockQuantity: 25, unit: "Boxes", expiryDate: "2024-10-31", form: "Box", maxCapacity: 100, reorderPoint: 30, storageLocation: { warehouse: "Lab Storage", aisle: "2", rack: "A", shelf: "03", zone: "B" }, handlingRequirements: ["Refrigerated"], vendorId: "V-3044", leadTime: "2-4 Days", unitPrice: 25.00 },
    { id: 25, itemName: "Ciprofloxacin 500mg", sku: "MED-CIP-500", category: "Medicine", department: "Pharmacy", supplier: "GlobalPharma", stockQuantity: 400, unit: "Boxes", expiryDate: "2025-05-12", form: "Tablet", maxCapacity: 1200, reorderPoint: 250, storageLocation: { warehouse: "Main Dispensary", aisle: "3", rack: "A", shelf: "02", zone: "A" }, handlingRequirements: ["Below 25°C"], vendorId: "V-1155", leadTime: "2-4 Days", unitPrice: 4.80 },
    { id: 26, itemName: "Stethoscopes", sku: "EQP-STH-01", category: "Equipment", department: "General", supplier: "MedEquip Global", stockQuantity: 120, unit: "Units", expiryDate: "N/A", form: "Unit", maxCapacity: 200, reorderPoint: 40, storageLocation: { warehouse: "Equipment Storage", aisle: "1", rack: "B", shelf: "02", zone: "C" }, handlingRequirements: [], vendorId: "V-2211", leadTime: "7-10 Days", unitPrice: 45.00 },
    { id: 27, itemName: "Cotton Swabs", sku: "SUP-CSW-01", category: "Medical Supplies", department: "Central Supply", supplier: "CarePlus Supplies", stockQuantity: 500, unit: "Boxes", expiryDate: "N/A", form: "Box", maxCapacity: 2000, reorderPoint: 300, storageLocation: { warehouse: "Supply Room", aisle: "4", rack: "A", shelf: "04", zone: "C" }, handlingRequirements: ["Dry Place"], vendorId: "V-6011", leadTime: "3-5 Days", unitPrice: 3.50 },
    { id: 28, itemName: "Petri Dishes", sku: "LAB-PET-01", category: "Lab Supplies", department: "Laboratory", supplier: "OpticLab", stockQuantity: 1500, unit: "Packs", expiryDate: "N/A", form: "Pack", maxCapacity: 4000, reorderPoint: 800, storageLocation: { warehouse: "Lab Storage", aisle: "1", rack: "D", shelf: "01", zone: "A" }, handlingRequirements: ["Fragile"], vendorId: "V-8033", leadTime: "5-7 Days", unitPrice: 12.00 },
    { id: 29, itemName: "Loratadine 10mg", sku: "MED-LOR-10", category: "Medicine", department: "Pharmacy", supplier: "PharmaCorp Inc.", stockQuantity: 95, unit: "Boxes", expiryDate: "2026-04-20", form: "Tablet", maxCapacity: 500, reorderPoint: 100, storageLocation: { warehouse: "Main Dispensary", aisle: "4", rack: "B", shelf: "03", zone: "A" }, handlingRequirements: ["Below 25°C"], vendorId: "V-1023", leadTime: "2-4 Days", unitPrice: 3.80 },
    { id: 30, itemName: "Blood Pressure Monitors", sku: "EQP-BPM-01", category: "Equipment", department: "General", supplier: "HeartTech", stockQuantity: 35, unit: "Units", expiryDate: "N/A", form: "Unit", maxCapacity: 100, reorderPoint: 20, storageLocation: { warehouse: "Equipment Storage", aisle: "2", rack: "A", shelf: "04", zone: "C" }, handlingRequirements: ["Fragile"], vendorId: "V-5099", leadTime: "10-14 Days", unitPrice: 65.00 }
];

export const getMockInventoryData = () => {
  return [...mockData];
};

export const getMockInventoryItemById = (id) => {
  return mockData.find(item => item.id === parseInt(id) || item.sku === id);
};

export const addMockInventoryItem = (item) => {
  const newItem = {
    ...item,
    id: mockData.length > 0 ? Math.max(...mockData.map(d => d.id)) + 1 : 1
  };
  mockData.unshift(newItem);
};

export const updateMockInventoryItem = (id, updatedItem) => {
  const index = mockData.findIndex(item => item.id === parseInt(id) || item.sku === id);
  if (index !== -1) {
    mockData[index] = { ...mockData[index], ...updatedItem };
    return mockData[index];
  }
  return null;
};

export const deleteMockInventoryItem = (id) => {
  mockData = mockData.filter(item => item.id !== parseInt(id) && item.sku !== id);
};

export const calculateStatus = (stock) => {
  if (stock === 0) return 'Out Of Stock';
  if (stock > 0 && stock <= 100) return 'Low Stock';
  return 'In Stock';
};

